version: '3'

services:
    db:
        image: quay.io/usr42/clair-db:latest
        restart: on-failure
    clair:
        image: quay.io/usr42/clair-local-scan:v2.0.2
        links:
        - db:postgres
        depends_on:
        - db
        restart: on-failure
    scanner:
        image: quay.io/usr42/clair-container-scan:latest
        links:
        - clair
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
        - clair
